# Generated by Django 5.2.6 on 2025-09-20 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Local date of the entry (one per user & day).', verbose_name='Date')),
                ('score', models.IntegerField(choices=[(-4, 'no comment ☠️'), (-3, 'unterirdisch 💀'), (-2, 'meh 😵\u200d💫'), (-1, 'mau 🙁'), (0, 'passt scho 😐'), (1, 'ganz okay 🙂'), (2, 'gut drauf 😎'), (3, 'geilo 🤩'), (4, 'geilomatico 🚀')], help_text='Mood score from -4 to +4.', verbose_name='Score')),
                ('note', models.CharField(blank=True, default='', help_text='Optional short comment (max. 280 chars).', max_length=280, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mood entry',
                'verbose_name_plural': 'Mood entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='idx_user_date')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_mood_per_user_per_date'), models.CheckConstraint(condition=models.Q(('score__gte', -4), ('score__lte', 4)), name='score_in_range')],
            },
        ),
    ]
